jenkins:
  agentProtocols:
  - "Diagnostic-Ping"
  - "JNLP4-connect"
  - "OperationsCenter2"
  - "Ping"
  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: false
  disableRememberMe: false
  markupFormatter:
    rawHtml:
      disableSyntaxHighlighting: true
  numExecutors: 0
unclassified:
  githubpluginconfig:
    configs:
    - name: "GitHub - CloudBees Days"
      credentialsId: "cbdays-github-token-secret"
      manageHooks: true
  globallibraries:
    libraries:
    - defaultVersion: "master"
      name: "cb-days"
      retriever:
        modernSCM:
          scm:
            github:
              credentialsId: "cbdays-github-token"
              repoOwner: "cloudbees-days"
              repository: "pipeline-library"
kube:
  podTemplatesConfiguration:
    templates:
      - name: nodejs-app
        label: nodejs-app
        inheritFrom: "default-jnlp"
        containers:
          - name: nodejs
            image: node:8.12.0-alpine
            ttyEnabled: true
            command: /bin/sh -c
            args: "cat"
            ttyEnabled: true
            resourceLimitCpu: "1"
            resourceLimitMemory: "1Gi"
            resourceRequestCpu: "500m"
            resourceRequestMemory: "512Mi"
      - name: jdk10
        label: jdk10
        inheritFrom: "default-jnlp"
        containers:
          - name: jdk10
            image: openjdk:10-jdk-slim-sid
            ttyEnabled: true
            command: /bin/sh -c
            args: "cat"
            ttyEnabled: true
            resourceLimitCpu: "1"
            resourceLimitMemory: "1Gi"
            resourceRequestCpu: "500m"
            resourceRequestMemory: "512Mi"
      - name: jdk8
        label: jdk8
        inheritFrom: "default-jnlp"
        containers:
          - name: jdk8
            image: openjdk:8-jdk-slim
            ttyEnabled: true
            command: /bin/sh -c
            args: "cat"
            ttyEnabled: true
            resourceLimitCpu: "1"
            resourceLimitMemory: "1Gi"
            resourceRequestCpu: "500m"
            resourceRequestMemory: "512Mi"
credentials:
  system:
    domainCredentials:
      - domain :
          name: "github.com"
          description: "GitHub"
        credentials:
          - string:
              scope: GLOBAL
              id: cbdays-github-token-secret
              description: "GitHub PAT for beedemo-ops from JCasC - secret text"
              secret: ${github-ops-token}
          - usernamePassword:
              scope: GLOBAL
              id: cbdays-github-token
              description: "GitHub PAT for beedemo-ops from JCasC"
              username: beedemo-ops
              password: ${github-ops-token}
